version: '3'

services:
  # client:
  #   build: ./client
  #   container_name: client
  #   depends_on:
  #     - phoenix
  #   ports:
  #     - 8080:8080
  phoenix:
    build: ./server
    environment:
        PG_USER: postgres
        PG_PWD: postgres
        PG_DB: postgres
        PG_HOST: db
    ports:
        - "4000:4000"
    networks:
      - database
    depends_on:
      - db
    networks:
      - "database"
    dns:
      - 8.8.8.8
      - 8.8.4.4
  db:
    image: "postgres:latest"
    ports:
        - "5430:5432"
    environment:
        POSTGRES_PASSWORD: postgres
    networks:
      - database
networks:
  database:
