version: '3'

services:
  # client:
  #   build: ./client
  #   container_name: client
  #   depends_on:
  #     - phoenix
  #   ports:
  #     - 8080:8080
  phoenix:
    build:
      context: ./server
    container_name: server
    environment:
      PG_USER: postgres
      PG_PWD: postgres
      PG_DB: time_manager_dev
      PG_PORT: 5432
      PG_HOST: localhost
      DATABASE_URL: postgres://postgres:postgres@db:5432/time_manager_dev
    ports:
      - 4000:4000
    restart: on-failure
    depends_on:
      - db
    networks:
      - "database"
    dns:
      - 8.8.8.8
      - 8.8.4.4
  db:
    build:
      context: ./db
    networks:
      - database
    ports:
      - 5432:5432
    command: tail -f /dev/null
networks:
  database:
volumes:
  postgres-data:
# POSTGRES_PASSWORD: example
# POSTGRES_USER: postgres
# PG_DATA: /var/lib/postgresql/data/pgdata
