version: '3'

services:
  # client:
  #   build: ./client
  #   container_name: client
  #   depends_on:
  #     - phoenix
  #   ports:
  #     - 8080:8080
  phoenix:
    build:
      context: ./server
    container_name: server
    environment:
      PG_USER: postgres
      PG_PWD: postgres
      PG_DB: time_manager
      PG_PORT: 5430
      PG_HOST: db
      DATABASE_URL: postgres://postgres@db:5430/time_manager
    ports:
      - 4000:4000
    restart: on-failure
    depends_on:
      - db
    networks:
      - "database"
  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    command: 'postgres -c "max_connections=200"'
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5430:5432
    networks:
      - "database"
networks:
  database:
volumes:
  postgres-data:
# POSTGRES_PASSWORD: example
# POSTGRES_USER: postgres
# PG_DATA: /var/lib/postgresql/data/pgdata
